version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: MyBoard
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  spring-boot-app:
    build:
      context: ./campuschool_backend
      dockerfile: Dockerfile
    container_name: campuschool-back
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/MyBoard
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567890

  react-app:
    build:
      context: ./campuschool
      dockerfile: Dockerfile
    container_name: reacampuschool-front
    ports:
      - "3000:3000"
