spring:
  datasource:
    url: jdbc:mysql://localhost:3306/highpitch
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.jdbc.time_zone: UTC
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

external:
  jwt:
    tokenSecretKey: musung
    tokenPrefix: Bearer/u0020
    accessKey: Authorization
    accessTokenExpirationTime: 1800000
    refreshKey: RefreshToken
    refreshTokenExpirationTime: 604800000
