name: Deploy to EC2

on:
  push:
    branches:
      - main  # 배포할 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Docker and Docker Compose
      run: |
        sudo yum update -y
        sudo amazon-linux-extras install docker
        sudo service docker start
        sudo usermod -a -G docker ec2-user
        sudo systemctl enable docker
        sudo yum install -y docker-compose
      
    - name: Build and push Docker images to Docker Hub
      run: |
        docker-compose -f path/to/your/docker-compose.yml build
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker-compose -f path/to/your/docker-compose.yml push
        
    - name: SSH into EC2 instance and pull Docker images
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          docker-compose -f /path/to/your/docker-compose.yml pull
          
    - name: Start Docker containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          docker-compose -f /path/to/your/docker-compose.yml up -d
        
    - name: Wait for services to start
      run: sleep 30
      
    - name: Test deployed application
      run: |
        # Run any tests you have
        
    - name: Clean up
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          docker-compose -f /path/to/your/docker-compose.yml down
