name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push

      - name: SSH into EC2 and Pull Docker Images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY}}
          script: |
            sudo docker-compose -f /path/to/your/docker-compose.prod.yml pull

      - name: SSH into EC2 and Restart Docker Containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY}}
          script: |
            sudo docker-compose -f /path/to/your/docker-compose.prod.yml up -d
